import type { CSSProperties } from "react";

/** Co-located styles for the Project Context page. */
export const s = {
  layout: { display: "flex", height: "calc(100vh - 52px)" } satisfies CSSProperties,
  rail: {
    width: 300,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
    minHeight: 0,
  } satisfies CSSProperties,
  railHead: { padding: "16px 16px 10px" } satisfies CSSProperties,
  railTitle: {
    fontSize: 11,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  railHint: { fontSize: 12, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  railTools: { display: "flex", alignItems: "center", gap: 8, marginTop: 12 } satisfies CSSProperties,
  railList: { flex: 1, overflow: "auto", padding: "0 8px 8px" } satisfies CSSProperties,
  item: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 10px",
    marginBottom: 2,
    borderRadius: 6,
    border: "none",
    textAlign: "left",
    cursor: "pointer",
    fontSize: 12,
    color: "var(--text-primary)",
    background: active ? "var(--bg-hover)" : "transparent",
  }),
  itemFolder: { color: "var(--text-muted)", fontSize: 11 } satisfies CSSProperties,
  railNote: { padding: "8px 12px", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  railFoot: {
    padding: "12px 16px",
    borderTop: "1px solid var(--border)",
    fontSize: 11,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" } satisfies CSSProperties,
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 24px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  tab: (active: boolean, disabled: boolean): CSSProperties => ({
    padding: "10px 14px",
    border: "none",
    background: "transparent",
    borderBottom: "2px solid " + (active ? "var(--accent)" : "transparent"),
    marginBottom: -1,
    fontSize: 13,
    fontWeight: active ? 600 : 500,
    color: active ? "var(--text-primary)" : "var(--text-muted)",
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.6 : 1,
  }),
  toolbarActions: { display: "flex", alignItems: "center", gap: 8, padding: "6px 0" } satisfies CSSProperties,
  mainHead: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "14px 24px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  fileName: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  usedBy: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  body: { flex: 1, overflow: "auto", padding: "24px 32px", fontSize: 14 } satisfies CSSProperties,
  center: { flex: 1, display: "grid", placeItems: "center", padding: 24 } satisfies CSSProperties,
} as const;
