import type { CSSProperties } from "react";

/** Co-located styles for the Onboarding Tour page. */
export const s = {
  page: { padding: "22px 28px 40px", maxWidth: 1200 } satisfies CSSProperties,
  headerRow: { display: "flex", alignItems: "flex-start", gap: 16, marginBottom: 18 } satisfies CSSProperties,
  headerText: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  h1: { fontSize: 22, fontWeight: 700 } satisfies CSSProperties,
  repoName: { color: "var(--accent)", fontFamily: "var(--font-mono)" } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-muted)", marginTop: 4 } satisfies CSSProperties,
  chips: { display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 } satisfies CSSProperties,
  actions: { display: "flex", gap: 8, flexShrink: 0 } satisfies CSSProperties,
  layout: { display: "flex", gap: 28, alignItems: "flex-start" } satisfies CSSProperties,
  toc: {
    width: 190,
    flexShrink: 0,
    position: "sticky",
    top: 16,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  tocLabel: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0.6,
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  tocLink: {
    display: "block",
    padding: "5px 8px",
    borderRadius: 6,
    fontSize: 13,
    color: "var(--text-secondary)",
    textDecoration: "none",
    background: "transparent",
    border: 0,
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    fontSize: 13,
  } satisfies CSSProperties,
  bannerError: { borderColor: "var(--crit)" } satisfies CSSProperties,
  bannerText: { flex: 1 } satisfies CSSProperties,
  card: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    scrollMarginTop: 16,
  } satisfies CSSProperties,
  cardHead: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "14px 16px",
    background: "transparent",
    border: 0,
    color: "var(--text-primary)",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  cardTitle: { flex: 1 } satisfies CSSProperties,
  cardBody: { padding: "0 16px 16px", fontSize: 13.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  rows: { display: "flex", flexDirection: "column", gap: 8, margin: 0, padding: 0, listStyle: "none" } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "flex-start",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  rowText: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  mono: { fontFamily: "var(--font-mono)", fontSize: 12.5, color: "var(--text-primary)", wordBreak: "break-all" } satisfies CSSProperties,
  why: { marginTop: 4, color: "var(--text-muted)" } satisfies CSSProperties,
  index: { fontFamily: "var(--font-mono)", color: "var(--text-muted)", minWidth: 20 } satisfies CSSProperties,
  score: {
    fontFamily: "var(--font-mono)",
    fontSize: 11,
    padding: "2px 7px",
    borderRadius: 999,
    border: "1px solid var(--border-strong)",
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  note: { fontSize: 12, color: "var(--text-muted)", marginBottom: 10 } satisfies CSSProperties,
  diagram: { marginTop: 12 } satisfies CSSProperties,
  skeletonCard: { padding: 16, display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  state: { marginTop: 24 } satisfies CSSProperties,
} as const;
