import type { CSSProperties } from "react";

/** Co-located styles for the shared attach-docs picker. */
export const s = {
  wrap: { padding: "20px 28px 40px", maxWidth: 1040 } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
  } satisfies CSSProperties,
  h2: { fontSize: 17, fontWeight: 700 } satisfies CSSProperties,
  filter: { marginLeft: "auto", width: 240 } satisfies CSSProperties,
  repoRow: { width: 280, marginBottom: 12 } satisfies CSSProperties,
  repoLabel: {
    display: "block",
    fontSize: 11,
    color: "var(--text-muted)",
    marginBottom: 4,
  } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 14 } satisfies CSSProperties,
  note: { fontSize: 13, color: "var(--text-muted)", marginBottom: 14 } satisfies CSSProperties,
  row: (attached: boolean, dragOver: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    marginBottom: 6,
    borderRadius: 8,
    border: `1px solid ${dragOver ? "var(--accent)" : "var(--border)"}`,
    background: attached ? "var(--accent-bg)" : "var(--bg-elevated)",
  }),
  handle: { color: "var(--text-muted)", cursor: "grab", display: "inline-flex" } satisfies CSSProperties,
  name: { fontSize: 13, fontWeight: 500, color: "var(--text-primary)" } satisfies CSSProperties,
  folder: { fontSize: 11, color: "var(--text-muted)" } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  arrows: { display: "flex", gap: 2 } satisfies CSSProperties,
  previewBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 10px",
    fontSize: 12,
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginTop: 14,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  overCap: {
    marginTop: 10,
    padding: "8px 12px",
    fontSize: 12,
    borderRadius: 6,
    color: "var(--warn)",
    border: "1px solid var(--warn)",
  } satisfies CSSProperties,
  errorBar: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    marginBottom: 10,
    fontSize: 12,
    color: "var(--crit)",
  } satisfies CSSProperties,
  serializes: { marginTop: 20, paddingTop: 14, borderTop: "1px solid var(--border)" } satisfies CSSProperties,
  serializesTitle: {
    fontSize: 11,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  serializesGroup: { marginTop: 10 } satisfies CSSProperties,
  serializesHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 4,
  } satisfies CSSProperties,
  serializesRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "3px 0",
    fontSize: 12,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  serializesOrder: { width: 20, color: "var(--text-muted)" } satisfies CSSProperties,
  serializesNote: { fontSize: 12, color: "var(--text-muted)", marginTop: 10 } satisfies CSSProperties,
  modalBody: { padding: 24, maxHeight: "70vh", overflow: "auto", fontSize: 14 } satisfies CSSProperties,
} as const;
