import type { CSSProperties } from "react";

/** Co-located styles for the version history and its inline diff. */
export const s = {
  wrap: { padding: "20px 28px 40px", maxWidth: 940 } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 14 } satisfies CSSProperties,
  row: (current: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 8,
    border: `1px solid ${current ? "var(--border-strong)" : "var(--border)"}`,
    background: "var(--bg-elevated)",
    marginBottom: 8,
  }),
  version: (current: boolean): CSSProperties => ({
    fontSize: 12.5,
    fontWeight: 700,
    color: current ? "var(--accent-text)" : "var(--text-secondary)",
    background: current ? "var(--accent-bg)" : "var(--bg-hover)",
    padding: "3px 9px",
    borderRadius: 6,
    flexShrink: 0,
  }),
  summary: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  note: {
    fontSize: 13,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  date: { fontSize: 11.5, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  stat: (color: string): CSSProperties => ({ fontSize: 11.5, color, flexShrink: 0 }),
  actions: { display: "flex", gap: 6, flexShrink: 0 } satisfies CSSProperties,
  diffPane: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    background: "var(--bg-base)",
    margin: "-2px 0 12px",
  } satisfies CSSProperties,
  diffLine: (bg: string, color: string): CSSProperties => ({
    display: "flex",
    gap: 10,
    padding: "1px 12px",
    fontSize: 12,
    lineHeight: "20px",
    fontFamily: "var(--font-mono)",
    background: bg,
    color,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  }),
  gutter: {
    width: 34,
    flexShrink: 0,
    textAlign: "right",
    color: "var(--text-muted)",
    userSelect: "none",
  } satisfies CSSProperties,
  sign: { width: 8, flexShrink: 0 } satisfies CSSProperties,
  gap: {
    padding: "4px 12px",
    fontSize: 11,
    color: "var(--text-muted)",
    background: "var(--bg-surface)",
    borderTop: "1px solid var(--border)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  identical: { padding: "10px 12px", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
