import type { CSSProperties } from "react";

export const s = {
  wrap: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 18,
    minWidth: 0,
  } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 14,
  } satisfies CSSProperties,
  headerIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  headerLabel: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  statsRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginBottom: 12,
  } satisfies CSSProperties,
  stats: {
    display: "flex",
    gap: 18,
    flexWrap: "wrap",
    fontSize: 14,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  stat: { display: "inline-flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  statIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  statValue: { fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  toggle: {
    display: "inline-flex",
    marginLeft: "auto",
    padding: 3,
    gap: 2,
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-primary)",
  } satisfies CSSProperties,
  toggleBtn: {
    padding: "4px 12px",
    border: "none",
    borderRadius: 6,
    background: "transparent",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  toggleBtnOn: {
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
    fontWeight: 600,
  } satisfies CSSProperties,
  muted: { fontSize: 13, color: "var(--text-muted)", margin: 0 } satisfies CSSProperties,
  notice: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "10px 12px",
    marginBottom: 14,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-hover)",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  noticeBody: { flex: 1 } satisfies CSSProperties,
  noticeTitle: {
    fontWeight: 600,
    color: "var(--text-primary)",
    marginBottom: 2,
  } satisfies CSSProperties,
} as const;
