import type { CSSProperties } from "react";

export const s = {
  list: { display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  symbolRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 10px",
    border: "none",
    borderRadius: 6,
    background: "transparent",
    cursor: "pointer",
    textAlign: "left",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  symbolRowOpen: { background: "var(--bg-hover)" } satisfies CSSProperties,
  chevron: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  codeIcon: { color: "var(--accent)", flexShrink: 0 } satisfies CSSProperties,
  symbol: { fontSize: 14, fontWeight: 600, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  count: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  body: { padding: "6px 0 10px 32px", minWidth: 0 } satisfies CSSProperties,
  callers: {
    listStyle: "none",
    margin: 0,
    padding: "2px 0",
    borderLeft: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  callerRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    color: "var(--text-secondary)",
    minWidth: 0,
  } satisfies CSSProperties,
  path: { minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  tick: { width: 8, height: 1, background: "var(--border)", flexShrink: 0 } satisfies CSSProperties,
  arrow: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  chips: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 10 } satisfies CSSProperties,
} as const;
